chore: Update 2023-06
mozilla-services/megaphone pull request #108
Opened 2023-06-23 23:30 UTC by jrconlin

* update dependencies (except diesel)
* move to edition 2021
* add .cargo/audit.toml file

2023-08-29 09:59 UTC, smarnach commented on .cargo/audit.toml
> +    "RUSTSEC-2021-0144", # Bound by rocket 0.4.11
We could also upgrade rocket to 0.5.0-rc.3, which should work just fine, and will require only minimal changes. This would allow us to use stable Rust.

2023-08-29 09:59 UTC, smarnach commented on rust-toolchain
> +nightly
I'd prefer to keep a specific version in here to keep builds reproducible.

2023-08-29 09:59 UTC, smarnach commented on Cargo.toml
> +sentry-failure = "0.21"
Is this still required? This PR migrates Megaphone off failure.

2023-08-29 17:38 UTC, jrconlin commented on .cargo/audit.toml
> +    "RUSTSEC-2021-0144", # Bound by rocket 0.4.11
Updating from 0.4 to 0.5.0-rc.3 requires more than minimal changes. 
As such, I recommend we stick with 0.4 for now.

2023-08-29 18:12 UTC, jrconlin commented on Cargo.toml
> +sentry-failure = "0.21"
Thanks! Cleaned up some of the other crates and comments as well.

2023-08-29 22:06 UTC, pjenvey requested changes

2023-08-29 22:06 UTC, pjenvey commented on src/auth.rs
> +        };
I put this and a couple minor changes in https://github.com/mozilla-services/megaphone/compare/update/2023-06...update/2023-06-pjenvey

2023-08-29 22:06 UTC, pjenvey commented on src/error.rs
> +pub type Result<T> = result::Result<T, HandlerError>;
This is now equivalent to `HandlerResult` so one of them should be killed

2023-08-29 22:25 UTC, jrconlin commented on src/error.rs
> +pub type Result<T> = result::Result<T, HandlerError>;
Cool, going to go with `HandlerResult` since it's already distinct.

2023-08-29 22:35 UTC, pjenvey approved these changes

2023-08-29 22:35 UTC, pjenvey commented on src/error.rs
> +            write!(f, "\n\nCaused by: {source}")?;
Oh and one more thing: it's possible this will be too chatty for certain Error's basic description in sentry but I'm willing to leave it for now.

2023-08-29 22:52 UTC, merged

2023-08-30 10:00 UTC, smarnach commented on .cargo/audit.toml
> +    "RUSTSEC-2021-0144", # Bound by rocket 0.4.11
I was mainly replying to your comments here, which sounded to me a bit like "I would like to upgrade these dependencies, but I can't" to me. I don't really care either way.